export const GET_TMDB_CONFIGURATION = 'GET_TMDB_CONFIGURATION';
export const GET_ISO639_1_CODES = 'GET_ISO639_1_CODES';
export const GET_ISO3166_1_CODES = 'GET_ISO3166_1_CODES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export const SET_SECTION_ATTRIBUTES = 'SET_SECTION_ATTRIBUTES';
